/**
 * Build-time content sync.
 *
 * Single source of truth for docs + version lives in the git-switcher repo:
 *   github.com/aksisonline/gitswitch  ->  docs/public/**.md  + docs/public/meta.json
 *
 * In local dev we read the sibling checkout (../git-switcher/docs/public).
 * In CI we sparse-clone just docs/public from GitHub.
 *
 * Outputs:
 *   content/docs/**  ← .mdx files for Fumadocs MDX to process (links rewritten)
 *   src/generated/meta.ts  ← VERSION + SIDEBAR for the landing page
 */
import { execSync } from 'node:child_process'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, relative } from 'node:path'

const REPO = 'aksisonline/gitswitch'
const REPO_URL = `https://github.com/${REPO}.git`
const FALLBACK_VERSION = 'v0.1.22'

const ROOT = join(import.meta.dir, '..')
const SIBLING = join(ROOT, '..', 'git-switcher', 'docs', 'public')
const TMP = join(ROOT, '.docs-cache')
const CONTENT_OUT = join(ROOT, 'content', 'docs')
const META_OUT = join(ROOT, 'src', 'generated', 'meta.ts')

type DocMeta = { groups: Array<{ label: string; items: Array<string> }> }

function resolveDocsDir(): string {
  if (existsSync(SIBLING)) {
    console.log(`[sync] using sibling docs: ${SIBLING}`)
    return SIBLING
  }
  console.log(`[sync] sibling not found, sparse-cloning ${REPO_URL}`)
  rmSync(TMP, { recursive: true, force: true })
  execSync(
    `git clone --depth 1 --filter=blob:none --sparse ${REPO_URL} ${TMP}`,
    { stdio: 'inherit' },
  )
  execSync(`git -C ${TMP} sparse-checkout set docs/public`, { stdio: 'inherit' })
  return join(TMP, 'docs', 'public')
}

async function fetchVersion(): Promise<string> {
  try {
    const headers: Record<string, string> = { 'User-Agent': 'gitswitch-web-build' }
    if (process.env.GITHUB_TOKEN) headers.Authorization = `Bearer ${process.env.GITHUB_TOKEN}`
    const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, { headers })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = (await res.json()) as { tag_name?: string }
    if (data.tag_name) {
      console.log(`[sync] latest release: ${data.tag_name}`)
      return data.tag_name
    }
    throw new Error('no tag_name')
  } catch (err) {
    console.warn(`[sync] version fetch failed (${String(err)}), using ${FALLBACK_VERSION}`)
    return FALLBACK_VERSION
  }
}

function walkMarkdown(dir: string, base = dir): Array<string> {
  const out: Array<string> = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) out.push(...walkMarkdown(full, base))
    else if (entry.endsWith('.md')) out.push(relative(base, full).replace(/\.md$/, ''))
  }
  return out
}

function rewriteLinks(body: string, slugSet: Set<string>): string {
  // Docs were authored for root-served layout (/cli/commands). Rewrite to /docs/cli/commands.
  return body.replace(
    /\[([^\]]*)\]\(\/([^)#]+)((?:#[^)]*)?)\)/g,
    (full, text: string, path: string, hash: string) => {
      if (path.startsWith('docs/')) return full
      return slugSet.has(path) ? `[${text}](/docs/${path}${hash})` : full
    },
  )
}

async function main() {
  const docsDir = resolveDocsDir()
  const metaPath = join(docsDir, 'meta.json')
  const meta: DocMeta = existsSync(metaPath)
    ? JSON.parse(readFileSync(metaPath, 'utf8'))
    : { groups: [] }

  const slugList = walkMarkdown(docsDir).filter((s) => s !== 'meta')
  const slugSet = new Set(slugList)

  // Wipe and re-generate content/docs so stale files don't linger.
  rmSync(CONTENT_OUT, { recursive: true, force: true })
  mkdirSync(CONTENT_OUT, { recursive: true })

  for (const slug of slugList) {
    const raw = readFileSync(join(docsDir, `${slug}.md`), 'utf8')
    const rewritten = rewriteLinks(raw, slugSet)
    const outPath = join(CONTENT_OUT, `${slug}.mdx`)
    mkdirSync(dirname(outPath), { recursive: true })
    writeFileSync(outPath, rewritten)
  }
  console.log(`[sync] wrote ${slugList.length} MDX files to content/docs/`)

  // Privacy policy — exposed via a static file for the privacy route.
  const privacyPath = join(docsDir, '..', 'privacy-policy.md')
  if (existsSync(privacyPath)) {
    const privacyOut = join(ROOT, 'src', 'generated', 'privacy.md')
    mkdirSync(dirname(privacyOut), { recursive: true })
    writeFileSync(privacyOut, readFileSync(privacyPath, 'utf8'))
    console.log('[sync] copied privacy-policy.md')
  }

  const version = await fetchVersion()

  // Sidebar ordering for use on landing page + docs nav via fumadocs.
  const sidebar = meta.groups.map((g) => ({
    label: g.label,
    items: g.items.filter((s) => slugSet.has(s)),
  }))

  mkdirSync(dirname(META_OUT), { recursive: true })
  writeFileSync(
    META_OUT,
    `// AUTO-GENERATED by scripts/sync-content.ts — do not edit\n` +
      `export const VERSION = ${JSON.stringify(version)} as const\n` +
      `export const SIDEBAR = ${JSON.stringify(sidebar)} as const\n`,
  )
  console.log(`[sync] wrote VERSION=${version} + SIDEBAR to src/generated/meta.ts`)
}

main().catch((err) => {
  console.error('[sync] fatal:', err)
  process.exit(1)
})
